export class Users {
  getUsers() {
    return {
      'data': [
        {
          id: 1,
          name: 'John Doe',
          avatar: 'https://randomuser.me/api/portraits/men/33.jpg',
          email: 'johndoe@gmail.com',
          role: 'Admin',
          title: 'Regional Paradigm Technician',
          department: 'Optimization',
          status: 'Active'
        },
        {
          id: 2,
          name: 'Jessie Nichols',
          avatar: 'https://randomuser.me/api/portraits/women/21.jpg',
          email: 'jessienichols@email.com',
          role: 'Admin',
          title: 'Regional Paradigm Technician',
          department: 'Optimization',
          status: 'Active',
        },
        {
          id: 3,
          name: 'Sara Smith',
          avatar: 'https://randomuser.me/api/portraits/women/23.jpg',
          email: 'sarasmit@email.com',
          role: 'Admin',
          title: 'Regional Paradigm Technician',
          department: 'Optimization',
          status: 'Active',
        },
        {
          id: 4,
          name: 'Sophie Fernandez',
          avatar: 'https://randomuser.me/api/portraits/women/32.jpg',
          email: 'sophiefernandez@email.com',
          role: 'User',
          title: 'Regional Paradigm Technician',
          department: 'Optimization',
          status: 'Active',
        },
        {
          id: 5,
          name: 'Jamie Dixon',
          avatar: 'https://randomuser.me/api/portraits/men/29.jpg',
          email: 'JamieDixon@email.com',
          role: 'User',
          title: 'Regional Paradigm Technician',
          department: 'Optimization',
          status: 'Active',
        },
        {
          id: 6,
          name: 'Dave Wallace',
          avatar: 'https://randomuser.me/api/portraits/men/22.jpg',
          email: 'davewallace@email.com',
          role: 'Sales',
          title: 'Regional Paradigm Technician',
          department: 'Optimization',
          status: 'Active',
        },
        {
          id: 7,
          name: 'Brent Jones',
          avatar: 'https://randomuser.me/api/portraits/men/98.jpg',
          email: 'BrentJones@email.com',
          role: 'Sales',
          title: 'Regional Paradigm Technician',
          department: 'Optimization',
          status: 'Active',
        },
        {
          id: 8,
          name: 'Ken Hart',
          avatar: 'https://randomuser.me/api/portraits/men/80.jpg',
          email: 'ken.hart@example.com',
          role: 'Sales',
          title: 'Regional Paradigm Technician',
          department: 'Optimization',
          status: 'Active',
        },
        {
          id: 9,
          name: 'Anne Bailey',
          avatar: 'https://randomuser.me/api/portraits/women/34.jpg',
          email: 'anne.bailey@example.com',
          role: 'Marketing',
          title: 'Regional Paradigm Technician',
          department: 'Optimization',
          status: 'Active',
        },
        {
          id: 10,
          name: 'Bobbie Burton',
          avatar: 'https://randomuser.me/api/portraits/women/84.jpg',
          email: 'bobbie.burton@example.com',
          role: 'Marketing',
          title: 'Regional Paradigm Technician',
          department: 'Optimization',
          status: 'Active',
        },
      ],
      'count': 100,
      'size': 50,
      'page': 1,
    }
  }
}